config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  root to: 'users#index'

  resources :users, only: [:destroy, :new, :create, :show, :update, :index]
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

    attr_reader :password
    validates :username, presence: true
    validates :password_digest, presence: { message: 'Password can\'t be blank'}
    validates :password, length: { minimum: 5, allow_nil: true }
    validates :email, :full_name, presence: true

    after_initialize :ensure_session_token


    has_one_attached :profile_picture





    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end


    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end



    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def reset_session_token!
        self.session_token = self.class.generate_session_token
        self.save!
        self.session_token
    end


    private

    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user

    def require_current_user
        redirect_to new_session_path if current_user.nil?
    end
    def login!(user)
        @current_user = user
        session[:session_token] = user.session_token
    end

    def logout!
        current_user.try(:reset_session_token!)
        session[:session_token] = nil 
    end

    def current_user
        return nil if session[:session_token].nil?
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController



    def new

    end

    def create

        user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password])

        if user.nil?
            flash[:error] = "Username/Password not valid"
            render :new
            # redirect_to new_session_path
        else
            login!(user)
            flash[:notice] = "Welcome back #{user.username}"
            redirect_to user_path(user)
        end
    end



    def destroy
        logout!
        redirect_to new_session_url


    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_current_user, except: [:new, :create]

    def index
        @users = User.all
        @user = User.new

    end

    def new
        @user = User.new
    end
    # def create
        # @user = User.new(user_params)

        # if @user.save
        #     login!(@user)
        #     flash[:notice] = "Welcome #{@user.username}"
        #     redirect_to user_path(@user)
        # else
        #     flash.now[:errors] = @user.errors.full_messages
        #     render :new
        # end

    # end

    def create
        @user = User.new(user_params)
    
        respond_to do |format|
          if @user.save
            format.html { redirect_to @user, notice: 'User was successfully created.' }
            format.js
            format.json { render json: @user, status: :created, location: @user }
          else
            format.html { render action: "new" }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
      end

    def show
        @user = User.find(params[:id])
    end

    def update
        @user  = User.find(params[:id])

        respond_to do |format|
            if @user.update(username: params[:user][:username])
                format.html { redirect_to @user, notice: 'User has been updated.'}
                format.js
                format.json { render json: @user, status: :created, location: @user }
            else
                format.html { render action: "new" }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @user  = User.find(params[:id])
        if @user.destroy
            respond_to do |format|
                format.html { redirect_to @user, notice: "user has been deleted." }
                format.js
                format.json { render json: @user, status: :deleted, location: @user}
            end
        end
    end




    private 
    
    def user_params
        params.require(:user).permit(:username, :password, :email, :full_name, :profile_picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>InstaClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

    <%= render "shared/nav" %>
    <% if flash[:errors]%>
    <div class="errors-container">
        <% flash[:errors].each do |err|%>
        <p class="error-msg"><%= err %></p>
        <% end %>
    </div>
    <% else %>
    <%= flash[:error] %>
    <%  end %>

    <% if flash[:notice] %>
    <p><%= flash[:notice] %> </p>
    <% end%>
    <% if !current_user.nil? %>
    <ul>
        <li>Logged in as <%= current_user.username %> </li>
        <li>
            <form action="<%= session_url %>" method="POST">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="hidden" value="delete" name="_method">
                <input type="submit" value="Log out">
            </form>
        </li>
    </ul>
    <% end %>
    <%= yield %>
</body>

</html>

app/views/shared/_nav.html.erb
<nav class="main-nav">
    <ul class="nav-links">
        <li class="nav-insta"><%= link_to "Instagram", users_url %></li>
        <li class="nav-link">
            <%= link_to users_url do %>
            <i class="fa fa-home"></i>
            <% end %>
        </li>
        <li class="nav-link"><i class="fa fa-envelope"></i></li>
        <li class="nav-link"><i class="fa fa-heart"></i></li>
        <li class="nav-link dropdown">
            <i class='fa fa-user'></i>

        </li>
    </ul>
</nav>

app/views/users/_user.html.erb
<li>
    <%= user.username %> <br />
    <%= link_to "delete", user, remote: true, method: :delete %>
</li>

app/views/users/create.js.erb
var users = document.querySelector("#users");
users.insertAdjacentHTML("beforeend", "<%= j render(@user) %>");


document.getElementById("new_user").reset();

app/views/users/destroy.js.erb
var users = document.querySelector("#users");

users.removeChild(users.childNodes[i], "beforeend", "<%= j render(@user) %>")

app/views/users/index.html.erb
<h1>All Users</h1>

<ul id="users">
    <%= render @users %>
</ul>


<%= form_for @user, url: users_url, id: "update-form", method: 'post', :remote => true do |form| %>
<%= form.label :username%>
<%= form.text_field :username %><br />
<%= form.label :email %>
<%= form.text_field :email %><br />
<%= form.label :password %>
<%= form.password_field :password%><br />
<%= form.label :full_name %>
<%= form.text_field :full_name %><br />
<%= form.submit %>
<% end %>

app/views/users/new.html.erb
<div class="signup-main-container">
    <div class="instagram-title signup-title">
        <h1>Ayesha</h1>
        <p class="description">Sign up to see photos and videos from your friends.</p>
    </div>
    <div class="signup-form">
        <form action="<%= users_url %>" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <div class="email-field">
                <input type="email" name="user[email]" placeholder="Email">
            </div>
            <div class="fullname-field">
                <input type="text" name="user[full_name]" placeholder="Full Name">
            </div>
            <div class="username-field">
                <input type="text" name="user[username]" id="username" placeholder="Username">
            </div>
            <div class="password-field">
                <input type="password" name="user[password]" placeholder="Password">
            </div>
            <div class="signup-btn">
                <input type="submit" value="Sign Up">
            </div>
        </form>
    </div>

</div>
<div class='login-link'>
    Have an account? <%= link_to "Login", new_session_url %>
</div>

app/views/users/show.html.erb
<h1>User Show page </h1>